const mongoose = require('mongoose');

const Members = mongoose.Schema({
    memberID:{
        type:String,
        required:true
    },
    title:{
        type:String,
        required:true
    },
    firstName:{
        type:String,
        required:true
    },
    middleName:{
        type:String
    },
    lastName:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    gender:{
        type:String,
        required:true
    },
    community:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    village:{
        type:String,
        required:true
    },
    state:{
        type:String,
        required:true
    },
    country:{
        type:String,
        required:true
    },
    membershipType:{
        type:String,
        required:true
    },
    corporationName:{
        type:String
    },
    isActive:{
        type:String,
        enum:['Y','N'],
        default:'N'
    },
    isFirstLogin:{
        type:String,
        enum:['Y','N'],
        default:'N'
    },
    isPaid:{
        type:String,
        enum:['Y','N'],
        default:'N'
    },
    isPaidatRegistration:{
        type:String,
        enum:['Y','N'],
        default:'N'
    }
},{
    timestamps:true
})

module.exports = mongoose.model('members',Members)